### Variables
@baseUrl = http://localhost:8080
@contentType = application/json

### Create User
POST {{baseUrl}}/user/create
Content-Type: {{contentType}}

{
  "name": "Jaider Rico",
  "email": "Jaider.Rico@example.com"
}

### Create Another User
POST {{baseUrl}}/user/create
Content-Type: {{contentType}}

{
  "name": "María González",
  "email": "maria.gonzalez@example.com"
}

### Test with different data
POST {{baseUrl}}/user/create
Content-Type: {{contentType}}

{
  "name": "Carlos Ruiz",
  "email": "carlos.ruiz@example.com"
}

### GET All Users
GET {{baseUrl}}/user/all


### GET all projects
GET {{baseUrl}}/project/all

### Post create project
POST {{baseUrl}}/project/create
Content-Type: {{contentType}}

{
  "name": "AgentesAi",
  "description": "StartUp AI",
  "ownerid": "d6d7d59a-a9c0-456-9e6f-e0dbbb9ca6ed"
}