### Variables
@baseUrl = http://localhost:8080
@contentType = application/json

### Create User
POST {{baseUrl}}/user/create
Content-Type: {{contentType}}

{
  "name": "Jaider Rico",
  "email": "Jaider.Rico@example.com"
}

### Create Another User
POST {{baseUrl}}/user/create
Content-Type: {{contentType}}

{
  "name": "María González",
  "email": "maria.gonzalez@example.com"
}

### Test with different data
POST {{baseUrl}}/user/create
Content-Type: {{contentType}}

{
  "name": "Carlos Ruiz",
  "email": "carlos.ruiz@example.com"
}

### GET All Users
GET {{baseUrl}}/user/all


### GET all projects
GET {{baseUrl}}/project/all


### Post create project
POST {{baseUrl}}/project/create
Content-Type: {{contentType}}

{
  "name": "AgentesAi",
  "description": "StartUp AI",
  "ownerid": "b75a2583-b832-48ce-9761-baefee10177c"
}


### POST create Task
POST {{baseUrl}}/task/create
Content-Type: {{contentType}}

{
  "title": "Listar Eventos",
  "description": "se deben listar todos los eventos del organizador",
  "project_id": "797262d4-b955-4d09-b5fa-46f7fe9b0b6e"
}

### GET all Tasks
GET {{baseUrl}}/task/all

### Delete
DELETE {{baseUrl}}/project/


###delete
DELETE {{baseUrl}}/task/